services:
  - type: web
    name: fullstack-app
    env: python
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build && cd ..
      pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: API_KEY
        value: "" # 値はRenderのダッシュボードで設定する
      - key: REACT_APP_API_BASE_URL
        value: https://your-backend-url.onrender.com # ここに実際のバックエンドURLを設定する
